[window]
opacity = 0.95
decorations="none"

[font]
size = 20
normal         =  { family = "UbuntuMono Nerd Font" }
bold           =  { family = "UbuntuMono Nerd Font" }
italic         =  { family = "UbuntuMono Nerd Font" }
bold_italic    =  { family = "UbuntuMono Nerd Font" }

[cursor]
style = {shape = "Block"}

[mouse]
hide_when_typing = true
